# Generated by Django 5.1.4 on 2024-12-26 17:20

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=utils.fields.OrderField(blank=True, verbose_name='Порядок модуля'),
        ),
    ]
