# Generated by Django 5.1.4 on 2024-12-26 17:22

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=utils.fields.OrderField(blank=True, default=0, verbose_name='Порядок элемента'),
        ),
    ]
