# Generated by Django 5.1.4 on 2024-12-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_content_options_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
